version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "20:00"
      timezone: "Europe/Paris"
    assignees:
      - "EDM115"
    commit-message:
      prefix: "[dependabot/npm] "
      include: "scope"
    labels:
      - "dependabot/npm"
    pull-request-branch-name:
      separator: "/"
    reviewers:
      - "EDM115"
