version = 1

exclude_patterns = ["senescalade/node_modules/**"]

[[analyzers]]
name = "docker"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = ["vue"]
  environment = [
    "nodejs",
    "browser"
  ]
  style_guide = "google"

[[analyzers]]
name = "secrets"

[[analyzers]]
name = "shell"

[[analyzers]]
name = "sql"

  [analyzers.meta]
  capitalisation_policy = "upper"
  comma_style = "trailing"
  indent_unit = "space"
  single_table_references = "consistent"
  tab_space_size = 4

