version = 1

exclude_patterns = [".nuxt/**", ".output/**", "node_modules/**", "wait-for-it.sh"]

[[analyzers]]
name = "docker"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  environment = [
    "nodejs",
    "browser"
  ]
  module_system = "es-modules"
  plugins = ["vue"]
  skip_doc_coverage = ["arrow-function-expression", "class-declaration", "class-expression", "function-declaration", "function-expression", "method-definition"]
  style_guide = "google"

[[analyzers]]
name = "secrets"

[[analyzers]]
name = "shell"

[[analyzers]]
name = "sql"

  [analyzers.meta]
  capitalisation_policy = "upper"
  comma_style = "trailing"
  indent_unit = "space"
  single_table_references = "consistent"
  tab_space_size = 2
