version = 1

[[analyzers]]
name = "docker"

[[analyzers]]
name = "javascript"
environment = ["browser"]
style_guide = "google"

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"
  type_checker = "mypy"

[[analyzers]]
name = "secrets"

[[analyzers]]
name = "shell"

  [analyzers.meta]
  dialect = "bash"

[[analyzers]]
name = "sql"

  [analyzers.meta]
  capitalisation_policy = "upper"
  comma_style = "trailing"
  indent_unit = "space"
  single_table_references = "consistent"
  tab_space_size = 4

