services:
  db:
    env_file:
      - .env
    image: mysql:8.0.37
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./db/create_user.sql:/docker-entrypoint-initdb.d/0_create_user.sql
      - ./db/create_db.sql:/docker-entrypoint-initdb.d/1_create_db.sql
      - ./db/instantiate_db.sql:/docker-entrypoint-initdb.d/2_instantiate_db.sql
      - ./db/insert_test.sql:/docker-entrypoint-initdb.d/3_insert_test.sql

  maildev:
    depends_on:
        - db
    image: maildev/maildev:2.1.0
    ports:
      - "1080:1080"

  senescalade:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - db
    env_file:
      - .env
    image: edm115/senescalade
    ports:
      - "80:56860"

volumes:
  db-data:
