<template>
  <div>
    <v-btn
      color="primary"
      class="ma-5"
    >
      primary
    </v-btn><br><br>
    <v-btn
      color="secondary"
      class="ma-5"
    >
      secondary
    </v-btn><br><br>
    <v-btn
      color="accent"
      class="ma-5"
    >
      accent
    </v-btn><br><br>
    <v-btn
      color="error"
      class="ma-5"
    >
      error
    </v-btn><br><br>
    <v-btn
      color="info"
      class="ma-5"
    >
      info
    </v-btn><br><br>
    <v-btn
      color="success"
      class="ma-5"
    >
      success
    </v-btn><br><br>
    <v-btn
      color="warning"
      class="ma-5"
    >
      warning
    </v-btn><br><br>
    <v-btn
      color="background"
      class="ma-5"
    >
      background
    </v-btn><br><br>
    <v-btn
      color="text"
      class="ma-5"
    >
      text
    </v-btn><br><br>
  </div>
</template>

<script setup>
</script>

<style scoped>
</style>
