# Generated by Django 5.0 on 2023-12-08 13:06

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Represents a database migration for the Django app.

    Attributes:
        initial (bool): Indicates if this migration is the initial migration for the app.
        dependencies (list): Specifies the dependencies of this migration on other migrations.
        operations (list): Contains the operations to be performed in this migration.
    """

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "idInscription",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("dateNaissance", models.DateField()),
                ("mail", models.EmailField(max_length=254)),
                ("password", models.CharField(max_length=100)),
                ("confirm_password", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "Inscription",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DataCalendar",
            fields=[
                ("idSeance", models.IntegerField(primary_key=True, serialize=False)),
                ("jour", models.CharField(max_length=50)),
                ("heureSeance", models.TimeField()),
                ("dureeSeance", models.TimeField()),
                ("typeSeance", models.CharField(max_length=100)),
                ("niveau", models.CharField(max_length=100)),
                ("nbPlaces", models.IntegerField()),
                ("nbPlacesRestantes", models.IntegerField()),
                ("professeur", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "Seance",
                "managed": False,
            },
        ),
    ]
