# Generated by Django 4.2.7 on 2023-11-30 16:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inscription", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={"managed": False},
        ),
    ]
