# Generated by Django 4.2.7 on 2023-11-30 16:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inscription", "0002_alter_customuser_options"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="customuser",
            table="inscription_customuser",
        ),
    ]
