# Generated by Django 5.0 on 2023-12-14 15:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inscription", "0003_alter_custompersonne_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="custompersonne",
            name="idPersonne",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="idInscription",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="datacalendar",
            name="idSeance",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
