# Generated by Django 5.0 on 2023-12-14 16:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "inscription",
            "0004_customuser_isadmin_alter_custompersonne_idpersonne_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={"managed": False},
        ),
    ]
