# Generated by Django 4.2.7 on 2023-12-07 14:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inscription", "0008_alter_customuser_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={"managed": True},
        ),
    ]
