name: Lints the code using Black code style, and pushes the changes back to the repo

on:
  schedule:
    - cron: '0 4 * * 6'
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Black-ify
        uses: psf/black@stable
        with:
          options: "-v -t py312 --safe --exclude .git .github"
      - name: Commit changes
        run: |
          d=`date '+%Y/%m/%dT%H:%M:%SZ'`
          git config --local user.email ${{ secrets.GH_EMAIL }}
          git config --local user.name ${{ secrets.GH_USERNAME }}
          git add -A
          git commit -m "Code style changed to Black at ${d}"
      - name: Push commit
        uses: ad-m/github-push-action@v0.8.0
        with:
          force: false
          directory: "."
          branch: ${{ github.ref }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
